export const types = Object.freeze({
    // Sync
    TASK_START_FETCHING: 'TASK_START_FETCHING',
    TASK_STOP_FETCHING: 'TASK_STOP_FETCHING',
    TASK_SET_FETCHING_ERROR: 'TASK_SET_FETCHING_ERROR',
    TASK_ADD: 'TASK_ADD',
    TASK_EDIT: 'TASK_EDIT',
    TASK_REMOVE: 'TASK_REMOVE',

    // Async
    TASK_FETCH: 'TASK_FETCH',
})