export const types = Object.freeze({
    LIST_START_FETCHING: 'LIST_START_FETCHING',
    LIST_STOP_FETCHING: 'LIST_STOP_FETCHING',
    LIST_SET_FETCHING_ERROR: 'LIST_SET_FETCHING_ERROR',
    LIST_FILL: 'LIST_FILL',

    LIST_FETCH_ASYNC: 'LIST_FETCH_ASYNC'
})